### PR TITLE
Fix for github link error in ARM and BICEP template

### PR DESCRIPTION
**Pull request by delynchoong**
Fix for error Cannot find source control token with name github during deployment

## Purpose

* ...

## Does this introduce a breaking change?

```
[ ] Yes
[x ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

Use Deploy to Azure to test
```

## What to Check
Verify that the following are valid
* Resources are successfully deployed without error

## Other Information
<!-- Add any other helpful information that may be needed here. -->

### CODE REVIEW

**Comment by mycaule** [comment]
Also encountered the same problem on my side
Cannot find SourceControlToken with name GitHub

**Comment by delynchoong** [comment]
@microsoft-github-policy-service agree [company="Microsoft"]

**Comment by delynchoong** [comment]
@microsoft-github-policy-service agree company="microsoft"

**Comment by delynchoong** [comment]
@microsoft-github-policy-service agree

**Comment by seesharprun** [comment]
@delynchoong, We have made this change as part of another PR #19. Thanks for your contribution.

**Pull request closed without merging**
